### ISSUE TITLE
Cannot read properties of null (reading 'name')

### ISSUE THREAD

**Issue by bustillos83** [adrianhajdin/banking#25]
Not sure what i am doing wrong but cannot pass this issue, everything seems fine but I keep getting runtime error. 

Error: Cannot read properties of null (reading 'name')

Source
components\ui\RightSidebar.tsx (14:68) @ name

  12 |       <div className="profile">
  13 |         <div className="profile-img">
> 14 |           <span className="text-5xl font-bold text-blue-500">{user.name[0]}</span>
     |                                                                    
  15 |         </div>
  16 |
  17 |         <div className="profile-details">

**Comment by albertomtferreira** [comment]
Hi @bustillos83, share your repository and maybe someone will be able to help you.

**Comment by bustillos83** [comment]
Done! I made it public. [](https://github.com/bustillos83/fb_banking)

**Comment by bustillos83** [comment]
![Screenshot 2024-06-17 154637](https://github.com/adrianhajdin/banking/assets/105611825/5c15ee4e-5246-4cb2-84f8-dce2e44cd746)

**Comment by bustillos83** [comment]
![Screenshot 2024-06-17 154810](https://github.com/adrianhajdin/banking/assets/105611825/610d868b-c939-4ae7-bf07-5d7734ab187d)

**Comment by albertomtferreira** [comment]
Hi @bustillos83, see the commit that I sent to you.

Also, while on early stages, I would suggest you to move all components out of the /ui folder. Leaving that folder only for the shadcn ui.

**Comment by bustillos83** [comment]
I saw the commit and thank you, the problem is when I do that, there is no error anymore but no data is being pulled either. 
![Screenshot 2024-06-18 002035](https://github.com/adrianhajdin/banking/assets/105611825/bddc3831-bc5d-4fdd-ad48-fbdc6cfd1c52)

**Comment by bustillos83** [comment]
stays on guess instead of showing up the login user

**Comment by bustillos83** [comment]
I fixed the issue, it was a typo, i had 'appwtrite-session' in my user actions instead of 'appwrite-session'.
