### ISSUE TITLE
Validation error sign up

### ISSUE THREAD

**Issue by bustillos83** [adrianhajdin/banking#33]
I keep getting this error when i try to sign up.

  status: 400,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      date: [Array],
      'content-type': [Array],
      'content-length': [Array],
      connection: [Array],
      'access-control-allow-origin': [Array],
      'x-request-id': [Array],
      'cf-cache-status': [Array],
      'set-cookie': [Array],
      server: [Array],
      'cf-ray': [Array]
    }
  },
  body: {
    code: 'ValidationError',
    message: 'Validation error(s) present. See embedded errors list for more details.',
    _embedded: { errors: [Array] }
  }
}

**Comment by promumyhero** [comment]
did u already fix this?, need help

**Comment by promumyhero** [comment]
i got the solution of this, u need to see a postalCode, a postalCode for NY, is 5 digit, so if u filled just 4 or more than 5, its gonna give you this errors

**Comment by bustillos83** [comment]
> i got the solution of this, u need to see a postalCode, a postalCode for NY, is 5 digit, so if u filled just 4 or more than 5, its gonna give you this errors

There is not way to fix it so it doesn't error out? i used a 55 digit code and i get this error

**Comment by bustillos83** [comment]
resolved, age format was wrong using '/' instead of '-'

**Comment by LazarosZiskos** [comment]
did anyone fix this? I am getting the same error no matter what i try to do. help pls
