### ISSUE TITLE
shadcn-ui is not recognized as an internal or external command operable program or batch file

### ISSUE THREAD

**Issue by joules65** [adrianhajdin/banking#54]
Everytime i write this into the terminal I'm thrown this message, yet I have my tailwind css installed on the application.

**Comment by AdamPilak** [comment]
I have the same issue. There might be a problem with the 0.9.0 version. Switching to shadcn-ui@0.8.0 and then running 'npx shadcn-ui@0.8.0 init' also works fine for me.

**Comment by Ayesha-Solanki15** [comment]
You can checkout this guide to resolve the issue
[](https://stackoverflow.com/questions/78934468/shadcn-ui-commands-on-terminal-is-not-working)
Worked for me!

**Comment by udhayasuresh** [comment]
> I have the same issue. There might be a problem with the 0.9.0 version. Switching to shadcn-ui@0.8.0 and then running 'npx shadcn-ui@0.8.0 init' works fine for me.

Thanks @AdamPilak it's working for me @0.8.0 version

**Comment by AbhishekKhangare24** [comment]
Thanks  @AdamPilak it's also working for me @0.8.0 version

**Comment by Avhijit-Nair** [comment]
Don't downgrade to 0.8.0 version, instead refer to the Stackoverflow link provided by @Ayesha-Solanki15 . In a nutshell, Shadcn changed their CLI tool name from `shadcn-ui` to `shadcn` , so every command will change from shadcn-ui to shadcn. Example - `npx shadcn-ui@latest` to `npx shadcn@latest`

**Comment by joelcoronah** [comment]
> Don't downgrade to 0.8.0 version, instead refer to the Stackoverflow link provided by @Ayesha-Solanki15 . In a nutshell, Shadcn changed their CLI tool name from `shadcn-ui` to `shadcn` , so every command will change from shadcn-ui to shadcn. Example - `npx shadcn-ui@latest` to `npx shadcn@latest`

Thats works for me! thanks

**Comment by TheCaptainCodes** [comment]
just use `shadcn` instead of `shad-cn`

**Comment by babually** [comment]
For me  it work
instead of `npx shadcn-ui@latest init`
se a specific package manager: `pnpm dlx shadcn-ui@latest init`

**Comment by hawarih** [comment]
> Don't downgrade to 0.8.0 version, instead refer to the Stackoverflow link provided by @Ayesha-Solanki15 . In a nutshell, Shadcn changed their CLI tool name from `shadcn-ui` to `shadcn` , so every command will change from shadcn-ui to shadcn. Example - `npx shadcn-ui@latest` to `npx shadcn@latest`

Thanks  [Avhijit-Nair](https://github.com/Avhijit-Nair) alot you save my time

**Comment by takudzwachinofunga** [comment]
> I have the same issue. There might be a problem with the 0.9.0 version. Switching to shadcn-ui@0.8.0 and then running 'npx shadcn-ui@0.8.0 init' works fine for me.

Thank you

**Comment by astopaal** [comment]
Use shadcn instead of shadcn-ui for new versions

**Comment by eddiesoft26** [comment]
> Don't downgrade to 0.8.0 version, instead refer to the Stackoverflow link provided by [@Ayesha-Solanki15](https://github.com/Ayesha-Solanki15) . In a nutshell, Shadcn changed their CLI tool name from `shadcn-ui` to `shadcn` , so every command will change from shadcn-ui to shadcn. Example - `npx shadcn-ui@latest` to `npx shadcn@latest`

You have just saved my soul. Thanks a lot
