### ISSUE TITLE
{user.name[0]} described as a null value

### ISSUE THREAD

**Issue by joules65** [adrianhajdin/banking#56]
in the footer section when i compile and run there is an error in the terminal under the name for {user.name[0]} and says cannot read properties of null 'name' even though the file doesn't seem to be screaming over any errors. Eventually  the if statement loggedOut for router.push; export const Footer = ({ user, type = 'desktop' }: FooterProps) => {
  const router = useRouter();
  const handleLogOut = async () => {
    const loggedOut = await logoutAccount();

    if(loggedOut) router.push('/sign-in')
  } 
the loggedOut is flaring and says an expression of type void cannot be tested for truthiness(if that's even a correct statement).

**Comment by joules65** [comment]
![Screenshot (69)](https://github.com/user-attachments/assets/d412a61b-9e28-4e18-95c2-55bb3339d5cc)

**Comment by ShadowRoot-ops** [comment]
did you found the solution i am encountering with the same issue

**Comment by ShadowRoot-ops** [comment]
when you go to home page directly without sign in or sign up it will through a null value. To go to the logged in user you have to sign in by going. http://localhost:3000/sign-in. http://localhost:3000/sign-up. Then log in using the email and password. then you will be directed to your dashboard. start working from there
