### ISSUE TITLE
Error: client does not have user consent to access the PRODUCT_TRANSACTIONS product

### ISSUE THREAD

**Issue by Rotaralexc** [adrianhajdin/banking#69]
Hello, I got the following error, for some reason I dont get the data for recent transactions in the home page.
Here is the error that I got:
![image](https://github.com/user-attachments/assets/38581c4e-4ead-43fb-972a-fcbdd7baa592)
![image](https://github.com/user-attachments/assets/ddefdd27-f6fb-4b9d-b5eb-f28e8743eeb5)
![image](https://github.com/user-attachments/assets/e8e4ee50-0ba8-4026-b2d8-a757ac4ec640)

Does anyone know how to fix this problem? 
I tried to clone the repo and had the same issue, also I recreated the database and checked for misspelling and still got the problem.
Thank you in advance!

**Comment by Rotaralexc** [comment]
Found out the solution, in order to fetch the transaction data you have to add this in code
![image](https://github.com/user-attachments/assets/872bdd9a-10d9-421c-9af0-bf36ca224b72)
After that deactivate the dwolla user, and delete the appwrite user data and it will work

**Comment by badya9a** [comment]
Bro, u saved me

**Comment by Coder-Sujal** [comment]
bro after change still i got the same error

**Comment by beginner154** [comment]
> bro after change still i got the same error

Yeah i changed that but still having the same error:

An error occurred while getting the account: TypeError: transactions is not iterable

**Comment by SerhatKaanManisali** [comment]
Thank you. 
Had the same issue.
It got fixed now.

**Comment by JavDaGreat** [comment]
is someone getting this error  ??  
i jst tested and clone the rep and add transactions inside user actions same error . 

AppwriteException: Invalid query: Attribute not found in schema: senderBankId
    at _Client.call (webpack-internal:///(rsc)/./node_modules/node-appwrite/dist/client.mjs:287:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Databases.listDocuments (webpack-internal:///(rsc)/./node_modules/node-appwrite/dist/services/databases.mjs:1625:12)
    at async $$ACTION_1 (webpack-internal:///(rsc)/./lib/actions/transaction.actions.ts:39:36)
    at async $$ACTION_1 (webpack-internal:///(rsc)/./lib/actions/bank.actions.ts:88:42)
    at async Home (webpack-internal:///(rsc)/./app/(root)/page.tsx:32:21) {
  code: 400,
  type: 'general_query_invalid',
  response: {
    message: 'Invalid query: Attribute not found in schema: senderBankId',
    code: 400,
    type: 'general_query_invalid',
    version: '1.6.0'
  }
}

**Comment by Daniel-Azil** [comment]
It means you haven't created the `senderBankId` attribute in Appwrite. Navigate to 5:52:45 in the [YouTube tutorial](https://www.youtube.com/watch?v=PuOVqP_cjkE&t=16200s) and create all the attributes for the transaction collection as shown in the tutorial.

**Comment by iOMJaiswal** [comment]
I am getting same error 

> bro after change still i got the same error

Rotaralexc @adrianhajdin

**Comment by AnilkumarKotyada** [comment]
why this error are how to reslove form them
![Screenshot 2024-11-28 003712](https://github.com/user-attachments/assets/a7bb5ead-faba-4596-97a3-e813aa467ecb)
![Screenshot 2024-11-28 003748](https://github.com/user-attachments/assets/44eb83fd-16f9-48fb-93ad-129ffde2cff4)

**Comment by CHrisEl-coder** [comment]
> why this error are how to reslove form them ![Screenshot 2024-11-28 003712](https://github.com/user-attachments/assets/a7bb5ead-faba-4596-97a3-e813aa467ecb) ![Screenshot 2024-11-28 003748](https://github.com/user-attachments/assets/44eb83fd-16f9-48fb-93ad-129ffde2cff4)

To solve this you need to add transactions and identity in your products array in the tokenParams that fetches accessToken, with this plaid gives the user access to get transactions... also there is no retroactive way to solve this for already created users that have accessTokens without access to transactions you have t delete the users and create a new one. 

Below is the Refactored Code   

try {
    const tokenParams = {
      user: {
        client_user_id: $id
      },
      client_name: `${firstName} ${lastName}`,
      products: ['auth', 'identity', 'transactions'],
      language: 'en',
      country_codes: ['US'],
      update: {reauthorization_enabled: true}
    }

**Comment by CHrisEl-coder** [comment]
Let me know if this solves your issue

**Comment by AnilkumarKotyada** [comment]
Okok
