### ISSUE TITLE
transactions is not iterable

### ISSUE THREAD

**Issue by beginner154** [adrianhajdin/banking#70]
Hey everyone!Having this kind of error after  5:08:45 stamp in the video.Error:
```
An error occurred while getting the account: TypeError: transactions is not iterable
    at $$ACTION_1 (webpack-internal:///(rsc)/./lib/actions/bank.actions.ts:120:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Home (webpack-internal:///(rsc)/./app/(root)/page.tsx:45:21)
```
Basically, i can not see any sample list of transactions in table form(shadcn) 
I checked bank.actions.ts where transactions are being declared ,found nothing wrong
Already struggling with it for 4 days

**Comment by SerhatKaanManisali** [comment]
Same here 🙋‍♂️
It has been working 2 weeks ago but suddenly I can't fetch any transactions anymore.
I tried going back to old commits in which it worked for sure but it hasn't fixed it either.
Must be an error or change from Plaid's side I guess.

**Comment by softyanshi** [comment]
Same here....Have u got the reason?? please share...

**Comment by beginner154** [comment]
@softyanshi reason in what sense?
Just have issue of transaction of being non iterable,in appwrite got all attributes in transactions ,still isn’t working

**Comment by softyanshi** [comment]
Oh I'm facing the same problem dunno how to figure it out

**Comment by softyanshi** [comment]
@beginner154 does your account says undefined? while using "console.log({accountsData ,account})

**Comment by beginner154** [comment]
@softyanshi no i do not have undefined in terminal
Btw try to add "transactions" to the products array in createLinkToken because apparently according to docs you need to include it 
```
  const tokenParams = {
      user: {
        client_user_id: user.$id,
      },
      client_name: `${user.firstName} ${user.lastName}`,

      products: ["auth","transactions"] as Products[],

      language: "en",

      country_codes: ["US"] as CountryCode[],
    };
 
```

**Comment by beginner154** [comment]
Just things i did to solve the ISSUE:
1.First i found some mispelled cases of "transactions".I wrote "transcations"(I am complete dumbass) instead in RecentTransactions.tsx other files,.env and 
in appwrite databases
2.I added transactions to the products array in tokenParams(as described earlier)

3.But MAIN thing that debbuged whole situation is I just cleared users data in appwrite ,dwolla sandbox and created new user,logged in and Wuhuu,everything is there.My theory is just that while creating new things and adding them to app might have caused some issues because of reloading such big and complex structure

So yeah try to delete current user to core and then create new one

**Comment by softyanshi** [comment]
@beginner154 thank you sooo sooo muchhh...even my problem got resolvedd......Im sooo happyyyy
